version: '3.0'

services:
#  mysql:
#    # 镜像名
#    image: mysql:5.7.25
#    # 容器名(以后的控制都通过这个)
#    container_name: mysql
#    # 重启策略
#    restart: always
#    environment:
#      # 时区上海
#      TZ: Asia/Shanghai
#      # root 密码
#      MYSQL_ROOT_PASSWORD: root
#      # 初始化数据库(后续的初始化sql会在这个库执行)
#      MYSQL_DATABASE: nacos_config
#      # 初始化用户(不能是root 会报错, 后续需要给新用户赋予权限)
#      MYSQL_USER: nacos
#      # 用户密码
#      MYSQL_PASSWORD: nacos
#      # 映射端口
#    ports:
#      - 3306:3306
#    volumes:
#      # 数据挂载
#      - /root/mysql/data/:/var/lib/mysql/
#      # 配置挂载
#      - /root/mysql/conf/:/etc/mysql/conf.d/
#      # 初始化目录挂载
#      - /root/mysql/init/:/docker-entrypoint-initdb.d/
#    command:
#      --default-authentication-plugin=mysql_native_password
#      --character-set-server=utf8mb4
#      --collation-server=utf8mb4_general_ci
#      --explicit_defaults_for_timestamp=true
#      --lower_case_table_names=1


  registry:
    image: registry
    restart: always
    volumes:
      - ./registry-data:/var/lib/registry
  ui:
    image: joxit/docker-registry-ui:static
    restart: always
    ports:
      - 8080:80
    environment:
      - REGISTRY_TITLE=私有仓库
      - REGISTRY_URL=http://registry:5000
    depends_on:
      - registry